Add FFI codelab
flutter/codelabs pull request #1170
Opened 2022-10-25 05:06 UTC by maks

Adding code for the Flutter plugin using FFI Codelab.

## Pre-launch Checklist

- [X] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [X] I signed the [CLA].
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] All existing and new tests are passing.

2022-10-25 22:32 UTC, domesticmouse commented on ffi_codelab/complete/msfa_plugin/CHANGELOG.md
> +## 0.0.1
Drop this file

2022-10-25 22:34 UTC, domesticmouse commented on ffi_codelab/complete/msfa_plugin/LICENSE
> +TODO: Add your license here.
Drop this file

2022-10-25 22:34 UTC, domesticmouse commented on ffi_codelab/complete/msfa_plugin/README.md
> +This project is a starting point for a Flutter
starting point? This is the completed version, yeah?

2022-10-25 22:37 UTC, domesticmouse commented on ffi_codelab/start/msfa_plugin/README.md
> +# msfa_plugin
Pretty much everything in this file should actually be in the codelab itself.

I'm curious on the steps taken to create this file. To aid in updating codelabs on Flutter version updates I need the steps to create the starting point, which I encode in a file like this one: https://github.com/flutter/codelabs/blob/main/adaptive_app/codelab_rebuild.yaml

2022-10-25 22:39 UTC, domesticmouse commented on .gitmodules
> +[submodule "ffi_codelab/complete/msfa_plugin/src/libmsfa"]
I don't use submodules in this repo, as a rule. So we are going to need to make a copy of the content of this sub-repo

2022-10-26 22:56 UTC, maks commented on ffi_codelab/complete/msfa_plugin/README.md
> +This project is a starting point for a Flutter
Oops yes, well spotted I'll fix that.

2022-10-26 22:56 UTC, maks commented on .gitmodules
> +[submodule "ffi_codelab/complete/msfa_plugin/src/libmsfa"]
Ok, no probs, I'll switch to just copying over instead of using submodules

2022-11-14 23:52 UTC, domesticmouse commented on .gitmodules
> +[submodule "ffi_codelab/complete/msfa_plugin/src/libmsfa"]
ping =)

2022-11-14 23:55 UTC, maks commented on .gitmodules
> +[submodule "ffi_codelab/complete/msfa_plugin/src/libmsfa"]
oh drats I thought I had removed the submodule, I'll fix that up!

2022-11-15 00:50 UTC, domesticmouse commented
I'mma gunna ask for one last change before landing this PR. Further fixups can be done in follow up PRs. 

Can you please add `ffi_codelab` to https://github.com/flutter/codelabs/blob/main/flutter_ci_script_stable.sh and https://github.com/flutter/codelabs/blob/main/flutter_ci_script_beta.sh to add this codelab to the GitHub Actions powered CI pipeline?

2022-11-15 04:51 UTC, domesticmouse requested changes

2022-11-15 04:51 UTC, domesticmouse commented on ffi_codelab/complete/msfa_plugin/example/lib/main.dart
> +// ignore_for_file: avoid_print
replace with `logDebug`

2022-11-15 04:51 UTC, domesticmouse commented on ffi_codelab/complete/msfa_plugin/example/lib/main.dart
> +import 'package:flutter/material.dart';
Please add a test to this package that exercises the plugin, otherwise it'll break and I'll never known

2022-11-15 05:21 UTC, domesticmouse commented
Btw, this PR is 68 commits behind master, please bring up to date

2022-11-15 05:54 UTC, domesticmouse requested changes

2022-11-15 05:54 UTC, domesticmouse commented on ffi_codelab/complete/msfa_plugin/.gitignore
> +# Miscellaneous
The `msfa` component of the path is redundant and meaningless. Drop.

2022-11-15 09:40 UTC, maks commented on ffi_codelab/complete/msfa_plugin/.gitignore
> +# Miscellaneous
@domesticmouse sorry I'm not sure I follow, do you mean I should just delete this `.gitignore` file?

2022-11-15 09:47 UTC, maks commented on ffi_codelab/complete/msfa_plugin/example/lib/main.dart
> +import 'package:flutter/material.dart';
Sorry, very good point! will do.

2022-11-15 10:00 UTC, maks commented on ffi_codelab/complete/msfa_plugin/example/lib/main.dart
> +import 'package:flutter/material.dart';
I added a very basic smoke test. I'm not sure I can test for actual functionality since I don't think the CI machines would have audio device support.

2022-11-15 10:04 UTC, maks commented
> Btw, this PR is 68 commits behind master, please bring up to date
@domesticmouse  Ah yes sorry forgot about that. I've merged in latest main now.

2022-11-15 22:33 UTC, domesticmouse commented
According to the CI pipeline it looks like the code needs some formatting:

```console
Analyzing msfa_plugin...
No issues found!
Changed example/lib/main.dart
Changed lib/msfa_plugin.dart
Formatted 4 files (2 changed) in 0.47 seconds.
```

2022-11-15 23:05 UTC, domesticmouse commented on ffi_codelab/complete/msfa_plugin/.gitignore
> +# Miscellaneous
I was just saying that having `msfa_plugin` as a sub directory of each step was redundant indirection. So I'm suggesting bringing everything up a level in the hierarchy.

2022-11-15 23:10 UTC, maks commented on ffi_codelab/complete/msfa_plugin/.gitignore
> +# Miscellaneous
ah gotcha, yes good point! will do 👍🏻

2022-11-16 01:12 UTC, domesticmouse commented on ffi_codelab/step_03/msfa_plugin/example/lib/main.dart
> +  _MyAppState createState() => _MyAppState();
This line is triggering the linters. Please modify to `State<MyApp> createState() => _MyAppState();`

2022-11-16 01:19 UTC, maks commented on ffi_codelab/step_03/msfa_plugin/example/lib/main.dart
> +  _MyAppState createState() => _MyAppState();
Yes found it and also fixed issue with dart format, I've just pushed up a fix

2022-11-16 05:06 UTC, domesticmouse commented on ffi_codelab/step_03/msfa_plugin/analysis_options.yaml
> +    - lib/*bindings_generated.dart
nit: trailing `\n` at EOF

2022-11-16 05:10 UTC, domesticmouse commented on ffi_codelab/complete/msfa_plugin/example/lib/main.dart
> +import 'package:flutter/material.dart';
Is there a way of confirming that the FFI'd code has been loaded without actually doing audio work?

2022-11-16 05:49 UTC, domesticmouse approved these changes

2022-11-16 05:57 UTC, maks commented on ffi_codelab/step_03/msfa_plugin/analysis_options.yaml
> +    - lib/*bindings_generated.dart
Oops, will fix it.

2022-11-16 09:58 UTC, merged

2022-11-16 09:58 UTC, domesticmouse commented on ffi_codelab/step_03/msfa_plugin/analysis_options.yaml
> +    - lib/*bindings_generated.dart
this can be done in a follow up PR +)