Adaptive Demo [Material 3 Reply App]
flutter/codelabs pull request #1214
Opened 2022-12-09 22:00 UTC by a-wallen

Out-of-the-box adaptive layouts were the most requested feature on desktop platforms in the Q3 2022 survey. The M3 Reply App is a good example of an app that adapts. This PR contains an implementation of the app.

https://user-images.githubusercontent.com/44445638/206802465-d38703be-13bd-42b4-b041-2e6d52436e10.mp4

https://user-images.githubusercontent.com/44445638/206802524-55d3d1c3-b34c-4aa8-ab77-8ae8dfe18724.mov

## Pre-launch Checklist

- [ ] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [X] I signed the [CLA].
- [X] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2022-12-11 00:52 UTC, domesticmouse requested changes

2022-12-11 00:52 UTC, domesticmouse commented on material3-reply/lib/models/name.dart
> +  String get initials => throw UnimplementedError();
drop?

2022-12-11 00:52 UTC, domesticmouse commented on material3-reply/lib/animation/constants.dart
> +enum MaterialDuration {
Please add a license header to this file and the other Dart files, per https://github.com/flutter/codelabs/blob/main/CONTRIBUTING.md#file-headers

Yes, I know the year is wrong, please see https://github.com/flutter/codelabs/pull/1208 for the fix =)

2022-12-11 00:52 UTC, domesticmouse commented on material3-reply/test/widget_test.dart
> +import 'package:flutter/material.dart';
I suspect this wont pass CI. 

Please add this project to https://github.com/flutter/codelabs/blob/main/flutter_ci_script_beta.sh and add a commented out line to https://github.com/flutter/codelabs/blob/main/flutter_ci_script_stable.sh

2022-12-12 22:32 UTC, domesticmouse commented
CI Issues:

```console
Analyzing material3-reply...

   info - lib/widgets/email_widget.dart:103:65 - The 'child' argument should be last in widget constructor invocations. Try moving the argument to the end of the argument list. - sort_child_properties_last
   info - lib/widgets/email_widget.dart:103:72 - Use 'const' with the constructor to improve performance. Try adding the 'const' keyword to the constructor invocation. - prefer_const_constructors
   info - lib/widgets/email_widget.dart:109:65 - The 'child' argument should be last in widget constructor invocations. Try moving the argument to the end of the argument list. - sort_child_properties_last
   info - lib/widgets/email_widget.dart:109:72 - Use 'const' with the constructor to improve performance. Try adding the 'const' keyword to the constructor invocation. - prefer_const_constructors

4 issues found.
```

2022-12-13 18:22 UTC, a-wallen commented
@domesticmouse thanks for the ping. I think that https://github.com/flutter/codelabs/pull/1214/commits/56e5fd5b24e5e97bfc386860fd5a152495b09693 should fix those analyzer errors.

2022-12-13 21:08 UTC, domesticmouse commented
And yet more errors. Please run `dart format` on the code, it's enforced by the CI.

2022-12-13 22:51 UTC, domesticmouse approved these changes

2022-12-13 23:29 UTC, merged