Update for breaking changes in IAP plugin
flutter/codelabs pull request #123
Opened 2021-05-12 09:48 UTC by renefloor

The in_app_purchases package will have some breaking changes soon. This PR adapts the codelab example for the coming breaking changes in flutter/plugins/pull/3877

2021-05-12 10:08 UTC, domesticmouse requested changes
I'm guessing you are waiting on an updated package to be published before we land this PR?

2021-05-12 10:08 UTC, domesticmouse commented on in_app_purchases/complete/app/pubspec.lock
> +      path: "../../../../flutter-plugins/packages/in_app_purchase/in_app_purchase"
I'm curious how this dependency path came about. Is the plug-in published yet?

2021-05-12 10:08 UTC, domesticmouse commented on in_app_purchases/complete/app/pubspec.yaml
> +    path: ../../../../../flutter-core/flutter-plugins/packages/in_app_purchase/in_app_purchase
This can't be published as is

2021-05-12 10:08 UTC, domesticmouse commented on in_app_purchases/step_06/app/pubspec.lock
> +      path: "../../../../flutter-plugins/packages/in_app_purchase/in_app_purchase"
Revert this too

2021-05-12 10:08 UTC, domesticmouse commented on in_app_purchases/step_06/app/pubspec.yaml
> +    path: ../../../../../flutter-core/flutter-plugins/packages/in_app_purchase/in_app_purchase
Ditto

2021-05-12 10:08 UTC, domesticmouse commented on in_app_purchases/step_07/app/pubspec.yaml
> +    path: ../../../../../flutter-core/flutter-plugins/packages/in_app_purchase/in_app_purchase
Ditto

2021-05-12 10:08 UTC, domesticmouse commented on in_app_purchases/step_08/app/pubspec.yaml
> +    path: ../../../../../flutter-core/flutter-plugins/packages/in_app_purchase/in_app_purchase
Ditto

2021-05-12 10:08 UTC, domesticmouse commented on in_app_purchases/step_09/app/pubspec.yaml
> +    path: ../../../../../flutter-core/flutter-plugins/packages/in_app_purchase/in_app_purchase
Ditto

2021-05-12 10:16 UTC, renefloor commented
> I'm guessing you are waiting on an updated package to be published before we land this PR?

Yep, the PR mentioned in the PR post needs to be released: flutter/plugins/pull/3877
The [platform interface](https://pub.dev/packages/in_app_purchase_platform_interface) is already published, the android, iOS and general implementations not yet.

2021-05-12 11:40 UTC, domesticmouse commented
I'd suggest marking this PR as WIP until the packages are published.

2021-05-13 00:37 UTC, domesticmouse commented on in_app_purchases/complete/app/pubspec.yaml
> +    path: ../../../../../flutter-core/flutter-plugins/packages/in_app_purchase/in_app_purchase
Quick thought, if you replace this path dependency with a [git dependency](https://dart.dev/tools/pub/dependencies#git-packages), we should be able to get this PR past the CI pipeline. 

That would enable us to land this PR and then update the codelab. Thoughts?

2021-05-13 08:43 UTC, domesticmouse approved these changes

2021-05-13 21:45 UTC, merged

2022-05-23 16:54 UTC, kleeb commented
any plans for making those samples working ?

```
src/iap.repository.ts:1:9 - error TS2724: '"firebase-admin/lib/firestore"' has no exported member named 'firestore'. Did you mean 'Firestore'?

import {firestore} from "firebase-admin/lib/firestore";
```

2022-05-24 00:16 UTC, domesticmouse commented
> any plans for making those samples working ?
> 
> ```
> src/iap.repository.ts:1:9 - error TS2724: '"firebase-admin/lib/firestore"' has no exported member named 'firestore'. Did you mean 'Firestore'?
> 
> import {firestore} from "firebase-admin/lib/firestore";
> ```

I'm part way through rebuilding the codelab to use a Dart back end running on Cloud Run, which is more suitable for us to maintain going forward.