Add minimum CI possible for dartpad workshops
flutter/codelabs pull request #133
Opened 2021-05-28 16:56 UTC by hrishikesh-kadam

This commit has following changes -
1. Add minimum CI possible for dartpad workshops
2. Fix minor issues in snippet and solution dart files
3. Fix links in README.md
4. Rearrange CODELABS list alphabetically amongst the scripts

2021-05-28 17:13 UTC, hrishikesh-kadam commented
I was going through the workshops of Google I/O and found a closing bracket `}` missing in the Null safety workshop's Step 13 Solution which led me to this repo.

Thought adding minimum CI possible as currently `flutter analyze` on single dart file maybe is not possible.
Please let me know if that is possible. I couldn't find it in the docs anywhere.

So added `flutter format --dry-run` on dart files which will at least fail the CI if it finds an issue parsing dart files.
And found 2 other minor issues in `dartpad_codelabs/src/getting_started_with_slivers/step_07/solution.dart ` and `dartpad_codelabs/src/example_flutter/step_02/snippet.dart`.

@domesticmouse As I am a first-time contributor to this repo, GitHub Action Checks will require approval.
I couldn't verify if the Checks are still passing on the GitHub Action.

2021-05-29 04:58 UTC, domesticmouse approved these changes
I'll trigger a full CI run next time I'm near a full sized computer

2021-05-31 05:38 UTC, domesticmouse requested changes

2021-05-31 05:38 UTC, domesticmouse commented on flutter_ci_script_beta.sh
> +      $FLUTTER format --dry-run solution.dart;
I suspect you should be passing `--set-exit-if-changed` instead of `--dry-run` to make the test fail if the code needs to be formatted.

2021-05-31 05:38 UTC, domesticmouse commented on flutter_ci_script_dev.sh
> +      $FLUTTER format --dry-run solution.dart;
ditto

2021-05-31 05:38 UTC, domesticmouse commented on flutter_ci_script_stable.sh
> +      $FLUTTER format --dry-run solution.dart;
ditto

2021-05-31 06:16 UTC, hrishikesh-kadam commented on flutter_ci_script_beta.sh
> +      $FLUTTER format --dry-run solution.dart;
I agree with you @domesticmouse on this.
But adding `--set-exit-if-changed` would require formatting the existing code shown on the DartPad Workshops of Google I/O 2021.
Although this will only make changes after the code is deployed on firebase.

If @RedBrogdon, @Piinks and @chunhtai agrees on this then I'll do the necessary.

If not then we can merge this at the moment and make formatting changes in subsequent PRs.

2021-05-31 06:21 UTC, domesticmouse commented on flutter_ci_script_beta.sh
> +      $FLUTTER format --dry-run solution.dart;
The codelabs have already been run, so I'm happy to go ahead and update the code. How bad is the damage?

2021-05-31 06:27 UTC, hrishikesh-kadam commented on flutter_ci_script_beta.sh
> +      $FLUTTER format --dry-run solution.dart;
Currently away from the system.
I'll update you on this in may be 4 hours.

2021-05-31 08:57 UTC, domesticmouse commented on flutter_ci_script_beta.sh
> +      $FLUTTER format --dry-run solution.dart;
No rush 😀

2021-05-31 09:29 UTC, hrishikesh-kadam commented on flutter_ci_script_beta.sh
> +      $FLUTTER format --dry-run solution.dart;
Done.

2021-05-31 09:29 UTC, hrishikesh-kadam commented on flutter_ci_script_dev.sh
> +      $FLUTTER format --dry-run solution.dart;
Done.

2021-05-31 09:29 UTC, hrishikesh-kadam commented on flutter_ci_script_stable.sh
> +      $FLUTTER format --dry-run solution.dart;
Done.

2021-05-31 09:32 UTC, hrishikesh-kadam commented
@domesticmouse Formatting changes in this commit - 3916ef2

2021-05-31 10:07 UTC, domesticmouse requested changes
There are a bunch of places where inserting a trailing comma will force the formatter to generate code akin to what was there before. Please fix.

2021-05-31 10:07 UTC, domesticmouse commented on dartpad_codelabs/src/getting_started_with_slivers/step_01/snippet.dart
> +    ));
Insert ,

2021-05-31 10:07 UTC, domesticmouse commented on dartpad_codelabs/src/getting_started_with_slivers/step_02/solution.dart
> +        ));
Insert ,

2021-05-31 10:07 UTC, domesticmouse commented on dartpad_codelabs/src/getting_started_with_slivers/step_03/solution.dart
> +        ));
Insert ,

2021-05-31 10:07 UTC, domesticmouse commented on dartpad_codelabs/src/getting_started_with_slivers/step_04/solution.dart
> +        ));
Insert ,

2021-05-31 10:07 UTC, domesticmouse commented on dartpad_codelabs/src/getting_started_with_slivers/step_05/solution.dart
> +        ));
Insert ,

2021-05-31 10:07 UTC, domesticmouse commented on dartpad_codelabs/src/getting_started_with_slivers/step_06/solution.dart
> +        ));
Insert ,

2021-05-31 10:07 UTC, domesticmouse commented on dartpad_codelabs/src/getting_started_with_slivers/step_07/solution.dart
> +        ));
Ditto

2021-05-31 10:07 UTC, domesticmouse commented on dartpad_codelabs/src/getting_started_with_slivers/step_08/snippet.dart
> +        ));
Ditto

2021-05-31 10:07 UTC, domesticmouse commented on dartpad_codelabs/src/inherited_widget/intro/snippet.dart
> +  ));
Ditto

2021-05-31 10:07 UTC, domesticmouse commented on dartpad_codelabs/src/inherited_widget/step_01/solution.dart
> +  ));
Ditto

2021-05-31 10:07 UTC, domesticmouse commented on dartpad_codelabs/src/inherited_widget/step_01/solution.dart
> +                    ))
Ditto

2021-05-31 13:11 UTC, hrishikesh-kadam commented
@domesticmouse I added trailing commas where ever necessary to reflect fewer formatting diffs.

I have a doubt, who should click the "Resolve conversation" button of the comments?
The reviewer or the contributor?

2021-05-31 21:15 UTC, domesticmouse requested changes
Still more `,` to add 🙃

2021-05-31 21:15 UTC, domesticmouse commented on dartpad_codelabs/src/inherited_widget/step_04/solution.dart
> +  ));
Add trailing , 🙃

2021-05-31 21:15 UTC, domesticmouse commented on dartpad_codelabs/src/inherited_widget/step_05/solution.dart
> +  ));
Ditto

2021-05-31 21:15 UTC, domesticmouse commented on dartpad_codelabs/src/inherited_widget/step_06/solution.dart
> +  ));
Ditto

2021-05-31 21:39 UTC, hrishikesh-kadam commented on dartpad_codelabs/src/inherited_widget/step_04/solution.dart
> +  ));
Added

2021-05-31 21:39 UTC, hrishikesh-kadam commented on dartpad_codelabs/src/inherited_widget/step_05/solution.dart
> +  ));
Added

2021-05-31 21:39 UTC, hrishikesh-kadam commented on dartpad_codelabs/src/inherited_widget/step_06/solution.dart
> +  ));
Added

2021-05-31 21:43 UTC, hrishikesh-kadam commented
@domesticmouse Last changes requested - https://github.com/flutter/codelabs/compare/f1ac15a680691bd36bece5beb6d31c615219ead8..c610a9014b31ea84a459f545c6627f6424a2449f

I prefer reset and push forcing so that a commit is viewed concrete in the future if required.

2021-05-31 23:14 UTC, domesticmouse requested changes
A couple more and we are good to go

2021-05-31 23:14 UTC, domesticmouse commented on dartpad_codelabs/src/inherited_widget/step_02/solution.dart
> +  ));
ditto

2021-05-31 23:14 UTC, domesticmouse commented on dartpad_codelabs/src/inherited_widget/step_03/solution.dart
> +  ));
ditto

2021-05-31 23:55 UTC, hrishikesh-kadam commented
@domesticmouse Last changes requested - https://github.com/flutter/codelabs/compare/c610a9014b31ea84a459f545c6627f6424a2449f..0418d9a2557f863fb597f217bfddbdc35e5e6538

I am sorry you had to review this multiple times.

2021-05-31 23:55 UTC, hrishikesh-kadam commented on dartpad_codelabs/src/inherited_widget/step_02/solution.dart
> +  ));
Added

2021-05-31 23:55 UTC, hrishikesh-kadam commented on dartpad_codelabs/src/inherited_widget/step_03/solution.dart
> +  ));
Added

2021-05-31 23:58 UTC, domesticmouse approved these changes

2021-06-01 00:14 UTC, domesticmouse commented
> I am sorry you had to review this multiple times.

All good, thanks for the PR!

2021-06-01 00:49 UTC, merged