Photos Sharing, attempt #2
flutter/codelabs pull request #137
Opened 2021-06-16 05:50 UTC by domesticmouse

This time with .gitignore files =)

2021-06-16 06:32 UTC, jfschmakeit requested changes
LGTM, just need to update the READMEs (and clean up the LICENSE files if needed)

2021-06-16 06:32 UTC, jfschmakeit commented on photos-sharing/final/CONTRIBUTING.md
> +# How to Contribute
Remove as there's already a CONTRIBUTING file at the top level.

2021-06-16 06:32 UTC, jfschmakeit commented on photos-sharing/final/README.md
> +See the `main` branch for the initial version of the app that you should check out to begin the
> `initial` directory

2021-06-16 06:32 UTC, jfschmakeit commented on photos-sharing/initial/README.md
> +Check out the `main` branch of this repository and follow the steps on
> `initial` directory

2021-06-16 06:32 UTC, jfschmakeit commented on photos-sharing/final/LICENSE
> +                                 Apache License
Is a dedicated LICENSE file needed in these sub directories?

2021-06-16 06:48 UTC, domesticmouse commented on photos-sharing/final/LICENSE
> +                                 Apache License
It’s a different license to most of the other codelabs in this repo, so I’d prefer to leave it as is. Keep OSPO happy. 😎

2021-06-16 07:32 UTC, domesticmouse commented on photos-sharing/initial/README.md
> +Check out the `main` branch of this repository and follow the steps on
done

2021-06-16 07:32 UTC, domesticmouse commented on photos-sharing/final/README.md
> +See the `main` branch for the initial version of the app that you should check out to begin the
done

2021-06-16 07:32 UTC, domesticmouse commented on photos-sharing/final/CONTRIBUTING.md
> +# How to Contribute
done for both `photos-sharing/initial` and `photos-sharing/final`

2021-06-17 01:35 UTC, jfschmakeit commented on photos-sharing/final/LICENSE
> +                                 Apache License
SGTM, thanks for clarifying!

2021-06-17 01:37 UTC, jfschmakeit approved these changes
Thanks, I think we are all good now!

2021-06-17 04:02 UTC, domesticmouse commented
Thanks JF!

2021-06-17 04:02 UTC, merged