Adding final state of pesto app.
flutter/codelabs pull request #1458
Opened 2023-03-05 07:39 UTC by jwill

Adds source code for Pesto Flutter app to be accompanied by codelab.

2023-03-05 08:12 UTC, domesticmouse requested changes

2023-03-05 08:12 UTC, domesticmouse commented on pesto_flutter/final/LICENSE
> +
Is this the first release of this code? If it is the first release I'd prefer it under the traditional flutter license used by most of the codelabs in this repo

2023-03-06 01:53 UTC, jwill commented on pesto_flutter/final/LICENSE
> +
Technically the 2nd release, first was a not-widely circulated release on material-foundation. Will remove local license in favor of top level one.

2023-03-06 02:10 UTC, domesticmouse requested changes
To re-license this code requires a fair amount of additional work to change over license headers. Given the code has been released already it's probably best not to re-license at this point. I'd suggest moving the Apache license block to the `pesto_flutter` base directory, as the contents of `final` are going to be replicated about 15 or so times. 

We probably don't need a contribution guide or code of conduct in the `final/docs` directory.

There are a set of images in `final/img` that appear to be supporting material for the codelab itself, not assets for the running application?

There are license headers applied to code that was generated by the template engine, which is going to make maintenance via a `codelab_rebuild` script more complicated going forward, as well.

2023-03-06 02:10 UTC, domesticmouse commented on pesto_flutter/final/lib/presentation/app.dart
> +// Licensed under the Apache License, Version 2.0 (the "License");
Replace with: https://github.com/flutter/codelabs/blob/main/CONTRIBUTING.md#file-headers

2023-03-06 02:10 UTC, domesticmouse commented on pesto_flutter/final/lib/presentation/router.dart
> +// Licensed under the Apache License, Version 2.0 (the "License");
Replace with: https://github.com/flutter/codelabs/blob/main/CONTRIBUTING.md#file-headers

2023-03-06 02:10 UTC, domesticmouse commented on pesto_flutter/final/lib/presentation/screens/notes.dart
> +// Licensed under the Apache License, Version 2.0 (the "License");
Replace with: https://github.com/flutter/codelabs/blob/main/CONTRIBUTING.md#file-headers

2023-03-06 02:10 UTC, domesticmouse commented on pesto_flutter/final/lib/presentation/screens/profile.dart
> +// Licensed under the Apache License, Version 2.0 (the "License");
Replace with: https://github.com/flutter/codelabs/blob/main/CONTRIBUTING.md#file-headers

2023-03-06 02:10 UTC, domesticmouse commented on pesto_flutter/final/lib/presentation/screens/recipe.dart
> +// Licensed under the Apache License, Version 2.0 (the "License");
Replace with: https://github.com/flutter/codelabs/blob/main/CONTRIBUTING.md#file-headers

2023-03-06 02:10 UTC, domesticmouse commented on pesto_flutter/final/lib/presentation/screens/recipes.dart
> +// Licensed under the Apache License, Version 2.0 (the "License");
Replace with: https://github.com/flutter/codelabs/blob/main/CONTRIBUTING.md#file-headers

2023-03-06 02:10 UTC, domesticmouse commented on pesto_flutter/final/lib/presentation/screens/root.dart
> +// Licensed under the Apache License, Version 2.0 (the "License");
Replace with: https://github.com/flutter/codelabs/blob/main/CONTRIBUTING.md#file-headers

2023-03-06 02:10 UTC, domesticmouse commented on pesto_flutter/final/lib/presentation/screens/settings.dart
> +// Licensed under the Apache License, Version 2.0 (the "License");
Replace with: https://github.com/flutter/codelabs/blob/main/CONTRIBUTING.md#file-headers

2023-03-06 02:10 UTC, domesticmouse commented on pesto_flutter/final/lib/presentation/theme.dart
> +// Licensed under the Apache License, Version 2.0 (the "License");
Replace with: https://github.com/flutter/codelabs/blob/main/CONTRIBUTING.md#file-headers

2023-03-06 02:10 UTC, domesticmouse commented on pesto_flutter/final/lib/presentation/widgets/adaptive_cards.dart
> +// Licensed under the Apache License, Version 2.0 (the "License");
Replace with: https://github.com/flutter/codelabs/blob/main/CONTRIBUTING.md#file-headers

2023-03-06 02:10 UTC, domesticmouse commented on pesto_flutter/final/lib/presentation/widgets/filter_list.dart
> +// Licensed under the Apache License, Version 2.0 (the "License");
Replace with: https://github.com/flutter/codelabs/blob/main/CONTRIBUTING.md#file-headers

2023-03-06 02:10 UTC, domesticmouse commented on pesto_flutter/final/lib/presentation/widgets/image_theme.dart
> +// Licensed under the Apache License, Version 2.0 (the "License");
Replace with: https://github.com/flutter/codelabs/blob/main/CONTRIBUTING.md#file-headers

2023-03-06 02:10 UTC, domesticmouse commented on pesto_flutter/final/lib/presentation/widgets/selected_chip.dart
> +// Licensed under the Apache License, Version 2.0 (the "License");
Replace with: https://github.com/flutter/codelabs/blob/main/CONTRIBUTING.md#file-headers

2023-03-06 02:10 UTC, domesticmouse commented on pesto_flutter/final/linux/main.cc
> +// Licensed under the Apache License, Version 2.0 (the "License");
Replace with: https://github.com/flutter/codelabs/blob/main/CONTRIBUTING.md#file-headers

2023-03-06 02:10 UTC, domesticmouse commented on pesto_flutter/final/linux/my_application.cc
> +// Licensed under the Apache License, Version 2.0 (the "License");
Replace with: https://github.com/flutter/codelabs/blob/main/CONTRIBUTING.md#file-headers

2023-03-06 02:10 UTC, domesticmouse commented on pesto_flutter/final/linux/my_application.h
> + * Licensed under the Apache License, Version 2.0 (the "License");
Replace with: https://github.com/flutter/codelabs/blob/main/CONTRIBUTING.md#file-headers

2023-03-06 02:10 UTC, domesticmouse commented on pesto_flutter/final/macos/Runner/AppDelegate.swift
> +// Licensed under the Apache License, Version 2.0 (the "License");
Replace with: https://github.com/flutter/codelabs/blob/main/CONTRIBUTING.md#file-headers

2023-03-06 04:16 UTC, domesticmouse commented
Actually, I'll land this as is and make the changes I need as I build out the steps. Thanks @jwill!

2023-03-06 04:17 UTC, domesticmouse approved these changes

2023-03-06 04:17 UTC, merged