[In-app Purchase] Fix wrong NonSubscriptionStatus enum orders
flutter/codelabs pull request #1768
Opened 2023-07-05 08:17 UTC by giandifra

For the [purchaseState](https://github.com/google/googleapis.dart/blob/14cc0510936ff24d96d2aef46938ebfd364896a2/generated/googleapis/lib/androidpublisher/v3.dart#L8893) the possible values are: `0. Purchased 1. Canceled 2. Pending`, but in the in-app purchase example at this [line](https://github.com/flutter/codelabs/blob/ea5a8e00895c1faed76d30528169c5c76cd9c3f4/in_app_purchases/complete/dart-backend/lib/google_play_purchase_handler.dart#L66) we convert the purchaseState into NonSubscriptionStatus in a wrong way.

```
Before
enum NonSubscriptionStatus {
  pending, // 0
  completed, // 1
  cancelled, // 2
}

After
enum NonSubscriptionStatus {
  completed, // 0
  cancelled, // 1
  pending, // 2
}
```

2023-07-06 09:59 UTC, domesticmouse commented
PTAL @miquelbeltran

2023-07-07 07:09 UTC, miquelbeltran commented
Hey @giandifra thanks for the fix!

I am thinking that it would be probably better to implement a method like the `subscriptionStatusFrom` (e.g. `nonSubscriptionStatusFrom`) so we can do a proper mapping of the values and not depend on the order of the enum values.

Do you think you can do the change?

2023-07-07 12:09 UTC, domesticmouse commented on in_app_purchases/complete/dart-backend/lib/iap_repository.dart
> +  // Payment completed
I suspect we don't need the comments. Thoughts @miquelbeltran ?

2023-07-07 13:04 UTC, miquelbeltran commented
A thing to keep in mind is that this method is only valid for the purchase state from the Google API, and it doesn't work for Apple.

So maybe this method and the `subscriptionStatusFrom` should be moved to the `google_play_purchase_handler.dart` and made private.

2023-07-07 13:40 UTC, miquelbeltran requested changes
I've requested some changes, I hope you don't mind.

The method `subscriptionStatusFrom` should also be moved to the `google_play_purchase_handler.dart` as a private method for consistency.

@domesticmouse once approved and before we merge, I'll have to apply these changes to the codelab document.

2023-07-07 13:40 UTC, miquelbeltran commented on in_app_purchases/complete/dart-backend/lib/google_play_purchase_handler.dart
> +}
Remove the comments, move the method at the end of the file.

2023-07-07 13:52 UTC, giandifra commented on in_app_purchases/complete/dart-backend/lib/google_play_purchase_handler.dart
> +}
subscriptionStatusFrom also has comments, do i have to remove them?

2023-07-07 13:58 UTC, miquelbeltran commented on in_app_purchases/complete/dart-backend/lib/google_play_purchase_handler.dart
> +}
I'd not, because the problem is that the numbers don't correspond directly to the enum value. e.g. value `1` means "Payment received" but it is translated as `SubscriptionStatus.active`.

In the case of a non-subscription, since the value is a direct match, it wouldn't be necessary IMO.

2023-07-07 15:14 UTC, miquelbeltran commented on in_app_purchases/step_08/dart-backend/lib/iap_repository.dart
> -  pending,
Seems that this was removed by mistake

2023-07-07 15:22 UTC, miquelbeltran commented
There's a formatting issue in one of the files, that's why CI is failing.

```
Changed lib/google_play_purchase_handler.dart
Formatted 9 files (1 changed) in 0.56 seconds.
```

You can fix it by running `dart format` over the codelab folder.

2023-07-09 07:03 UTC, domesticmouse commented
> @domesticmouse once approved and before we merge, I'll have to apply these changes to the codelab document.

@miquelbeltran I think you are empowered to LGTM and land a change that isn't your own. =)

2023-07-10 06:18 UTC, miquelbeltran requested changes

2023-07-10 06:18 UTC, miquelbeltran commented on in_app_purchases/step_08/dart-backend/lib/iap_repository.dart
> -  pending,
This change is still pending, blocks the PR

2023-07-10 06:18 UTC, miquelbeltran commented on in_app_purchases/step_00/dart-backend/lib/iap_repository.dart
> +  pending,
This change is still pending, blocks the PR

2023-07-10 13:55 UTC, miquelbeltran requested changes
Sorry, there is a still a consistency problem. The method `subscriptionStatusFrom` was removed from the `iap_repository.dart` file, but this method is still present in the steps 00, 07 and 08. It should be removed from all steps (as well as the complete example), and then added in the `google_play_purchase_handler.dart` in the step 09.

Looks like I cannot make changes into your main branch, so I cannot do that fix myself.

2023-07-11 07:00 UTC, miquelbeltran approved these changes
I think this looks good now :) I will have to update the codelab document before merging, will do in the upcoming days

2023-07-11 12:08 UTC, miquelbeltran commented
@domesticmouse I did the document changes too, and I know you told me I can land this, but I want to be sure it is OK before you publish the updated document.

2023-07-11 22:58 UTC, domesticmouse approved these changes

2023-07-11 22:59 UTC, domesticmouse commented
I'll land this with the updated codelab

2023-07-13 04:30 UTC, domesticmouse commented
Googlers: cl/547677600

2023-07-19 03:00 UTC, merged