Add IDX
flutter/codelabs pull request #2253
Opened 2024-10-23 23:19 UTC by domesticmouse

PTAL @rodydavis

## Pre-launch Checklist

- [ ] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [ ] I signed the [CLA].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md

2024-10-24 01:51 UTC, domesticmouse commented
FWIW, the red CI status has nothing to do with this PR. It will be fixed once #2254 lands and is integrated

2024-12-03 21:31 UTC, rodydavis requested changes

2024-12-03 21:31 UTC, rodydavis commented on .idx/dev.nix
> +    pkgs.flutter
Not needed as flutter is preinstalled!

2024-12-03 21:31 UTC, rodydavis commented on .idx/dev.nix
> +        updateStable = "flutter channel stable && flutter upgrade && flutter pub get";
Should already be on stable

2024-12-03 21:31 UTC, rodydavis commented on .idx/dev.nix
> +      onStart = {
Only needs to be onCreate

2024-12-06 00:57 UTC, domesticmouse commented on .idx/dev.nix
> +        updateStable = "flutter channel stable && flutter upgrade && flutter pub get";
I'm being explicit, with the intent that I can change the branch to `beta` and `main` while doing the maintenance work required to get ready for a new release

2024-12-06 00:58 UTC, domesticmouse commented
PTAL @rodydavis

2024-12-06 02:03 UTC, rodydavis commented on .idx/dev.nix
> +        updateStable = "flutter channel stable && flutter upgrade && flutter pub get";
You can rerun the onCreate hooks with IDX command palette!

2024-12-06 02:04 UTC, rodydavis approved these changes
LGTM

2024-12-06 04:13 UTC, merged