`webview_flutter`: add Step 12 (loading assets, file, HTML string)
flutter/codelabs pull request #266
Opened 2022-01-13 11:56 UTC by JDDV

Adds the implementation as described in the codelab for the webview_flutter.
This PR adds functionality for loading and displaying HTML/CSS assets, files or HTML from a String.

## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2022-01-13 14:47 UTC, JDDV commented
@domesticmouse Step 12 is added to the codelab and the code is done as well and ready for review. The Flutter CI checks on the beta channel seems to go wrong, looks like it's because of another codelab?

2022-01-15 09:05 UTC, domesticmouse commented
@JDDV I have a fix out for the issues on beta CI: https://github.com/flutter/codelabs/pull/267

2022-01-15 09:11 UTC, domesticmouse requested changes
Please rebuild `step_12` from `step_11`.

2022-01-15 09:11 UTC, domesticmouse commented on webview_flutter/step_12/pubspec.yaml
> +  sdk: ">=2.12.0 <3.0.0"
I'm curious which version of Flutter this project was created with.

2022-01-15 09:11 UTC, domesticmouse commented on webview_flutter/step_12/pubspec.yaml
> +name: step_12
I'd prefer if `step_12` was created from `step_11` like this:

```console
$ cp -R step_11 step_12
```

This will make sure a bunch of incidental changes aren't introduced that have to be reconciled later.

2022-01-17 01:00 UTC, domesticmouse commented
Please update this PR to fix CI

2022-01-19 00:25 UTC, albertodev01 reviewed
Got some minor suggestions but looks good!

2022-01-19 00:25 UTC, albertodev01 commented on webview_flutter/step_12/lib/src/navigation_controls.dart
> +  const NavigationControls({required this.controller, Key? key})
I would move the key first and add a comma at the end

```suggestion
  const NavigationControls({
    Key? Key,
    required this.controller,
  }) : super(key: key);
```

2022-01-19 00:25 UTC, albertodev01 commented on webview_flutter/step_12/lib/src/web_view_stack.dart
> +  const WebViewStack({required this.controller, Key? key}) : super(key: key);
Same here, Flutter generally puts the Key param first

2022-01-19 00:25 UTC, albertodev01 commented on webview_flutter/step_12/test/widget_test.dart
> +    await tester.pumpWidget(const MaterialApp(home: WebViewApp()));
If you are not goin to write any test, smoke this at least

```suggestion
    await tester.pumpWidget(const MaterialApp(home: WebViewApp()));
    
    // smoke test
    expect(find.byType(WebViewApp), findsOneWidget);
```

2022-01-19 00:50 UTC, domesticmouse commented on webview_flutter/step_12/lib/src/navigation_controls.dart
> +  const NavigationControls({required this.controller, Key? key})
Hilariously we have been putting the Key parameter last. @RedBrogdon do we have any particular feelings on this? We should probably be consistent (and create a lint to enforce the consistency).

2022-01-19 01:24 UTC, albertodev01 commented on webview_flutter/step_12/lib/src/navigation_controls.dart
> +  const NavigationControls({required this.controller, Key? key})
If I am correct, there currently is a lint to ensure that `child` is always last, but nothing for `key` as far as I  know

2022-01-20 09:46 UTC, JDDV commented on webview_flutter/step_12/pubspec.yaml
> +  sdk: ">=2.12.0 <3.0.0"
Updated to the newest version, this PR was made using version 2.5 I think

2022-01-20 09:51 UTC, JDDV commented on webview_flutter/step_12/lib/src/navigation_controls.dart
> +  const NavigationControls({required this.controller, Key? key})
I changed the order of the parameters in this PR. @domesticmouse  do you want me to make a different PR for the other steps that also have the 'wrong' order of parameters and update that. I can also add the smoke test mentioned by @albertodev01  for all the others step too in that PR.

2022-01-21 04:41 UTC, domesticmouse approved these changes

2022-01-21 08:50 UTC, domesticmouse commented on webview_flutter/step_12/lib/src/navigation_controls.dart
> +  const NavigationControls({required this.controller, Key? key})
I think the important thing is to be consistent through out the codelab. I don't have a preference one way or the other, as long as it stays stable for the length of the codelab.

2022-01-25 21:14 UTC, merged