Updated codelab: Write a Flutter desktop application Codelab (github package version)
flutter/codelabs pull request #270
Opened 2022-01-24 14:04 UTC by miquelbeltran

@domesticmouse @RedBrogdon 

This is the matching PR to the changes in the document "Write a Flutter desktop application Codelab (github package version)"

Some notes:

- I moved the codelab project from `github-graphql-client` to `github-client`.
- All steps are created from scratch using the latest flutter beta, to ensure being as recent as possible.
- Screenshots in the document has been updated to match the app. There should not be any reference to graphql anymore.
- Although the GitHub Dart package provides its own OAuth2 auth logic, I kept the original one and used the resulting access token instead to configure the GitHub Dart package.

## Pre-launch Checklist

- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

2022-01-24 14:11 UTC, miquelbeltran commented
I realized that the checks fail because I used flutter beta and the CI expect an SDK version or 2.15.1 max

2022-01-24 14:15 UTC, miquelbeltran commented
Note that all the `−547,691` changes are due to the graphql generated code being removed :)

2022-01-25 02:53 UTC, domesticmouse commented
Can you please change https://github.com/miquelbeltran/codelabs/blob/mb-github-client/flutter_ci_script_beta.sh#L15 and https://github.com/miquelbeltran/codelabs/blob/mb-github-client/flutter_ci_script_stable.sh#L15 to reflect the name change of the codelab?

2022-01-25 14:21 UTC, miquelbeltran commented
done!

2022-01-25 21:12 UTC, domesticmouse commented
Looks like the CI isn't happy:

```console
== Testing 'github-client/window_to_front'
Analyzing window_to_front...

  error - test/window_to_front_test.dart:21:32 - The getter 'platformVersion' isn't defined for the type 'WindowToFront'. Try importing the library that defines 'platformVersion', correcting the name to the name of an existing getter, or defining a getter or field named 'platformVersion'. - undefined_getter
   info - test/window_to_front_test.dart:11:39 - Avoid annotating types for function expression parameters. - avoid_types_on_closure_parameters
```

2022-01-26 07:29 UTC, miquelbeltran commented
I removed the test template from the window_to_front project

2022-01-27 02:08 UTC, domesticmouse commented
I realise this is going to be a PITA, but can we split the adding of the new codelab and deleting the old codelab into two separate PRs? I'm going to need to play an interesting game of sequencing to get this change to land right.

(There are links in the codelab that point at incorrect URLs, but I need to land the new codelab to make sure the fixups are correct, before deleting the old codelab and old code)

2022-01-27 02:11 UTC, domesticmouse commented
Also, you've updated the Copyright lines, even though in some cases it was only a move. Please revert

2022-01-27 03:35 UTC, domesticmouse commented
Actually, the list of changes for macOS was kinda silly, so I've pushed a cleanup version to this PR.

2022-01-27 04:15 UTC, domesticmouse requested changes
A couple of change required

2022-01-27 04:15 UTC, domesticmouse commented on github-client/step_06/README.md
> +# github_client
plz delete

2022-01-27 04:15 UTC, domesticmouse commented on github-client/step_06/lib/github_oauth_credentials.dart
> +// Copyright 2022 Google LLC
please revert this date change

2022-01-27 04:15 UTC, domesticmouse commented on github-client/step_06/lib/main.dart
> +// Copyright 2022 Google LLC
please revert

2022-01-27 04:15 UTC, domesticmouse commented on github-client/step_07/README.md
> +# github_client
please delete this file

2022-01-27 04:15 UTC, domesticmouse commented on github-client/step_07/lib/github_oauth_credentials.dart
> +// Copyright 2022 Google LLC
please revert this change

2022-01-27 04:15 UTC, domesticmouse commented on github-client/step_07/lib/main.dart
> +// Copyright 2022 Google LLC
please revert this change

2022-01-27 05:11 UTC, miquelbeltran commented
Going to take care of those asap

2022-01-27 05:34 UTC, domesticmouse commented
Thanks!

2022-01-27 07:10 UTC, domesticmouse approved these changes

2022-01-27 07:14 UTC, merged

2022-01-27 07:16 UTC, domesticmouse commented
Thanks @miquelbeltran