Initial Cookbook commit, includes gradient bubbles, expandable FAB, and download button.
flutter/codelabs pull request #41
Opened 2021-01-13 00:49 UTC by matthew-carroll

Initial Cookbook commit, includes gradient bubbles, expandable FAB, and download button.

2021-01-13 01:22 UTC, domesticmouse approved these changes

2021-01-13 03:42 UTC, domesticmouse commented
Are we meant to be on stable or beta?

```
Because vgv_flutter_cookbook requires SDK version >=2.12.0-0 <3.0.0, version solving failed.
```

2021-01-13 04:49 UTC, matthew-carroll commented
@domesticmouse I think the VGV project is either on dev or master....

2021-01-13 07:13 UTC, RedBrogdon requested changes
A bunch of little nits, for the most part. The meat of the code looks great.

2021-01-13 07:13 UTC, RedBrogdon commented on cookbook/lib/examples/gradient_bubbles.dart
> +// --- Mock Data Generation ---
Don't need this comment.

2021-01-13 07:13 UTC, RedBrogdon commented on cookbook/lib/examples/gradient_bubbles.dart
> +    data = MessageGenerator.generate(60, 1337);
😆

2021-01-13 07:13 UTC, RedBrogdon commented on cookbook/lib/main.dart
> +            leading: UnconstrainedBox(
What's the function of the UnconstrainedBox here? I would have expected a ListTile to hand an Icon in its leading property with no trouble.

2021-01-13 07:13 UTC, RedBrogdon commented on cookbook/pubspec.yaml
> +name: vgv_flutter_cookbook
No disrespect to VGV intended, but I'd prefer `flutter_cookbook` as the package name for simplicity's sake.

2021-01-13 07:13 UTC, RedBrogdon commented on cookbook/pubspec.yaml
> +description: VGV Flutter Cookbook Examples
"Source project for the design examples in the Flutter cookbook."

2021-01-13 07:13 UTC, RedBrogdon commented on cookbook/pubspec.yaml
> +  golden_toolkit: ^0.9.0-nullsafety.0
I believe the last time we talked, the plan was to leave golden testing out of the project, in which case this dependency can go. If I've got that wrong, though, ignore me.

2021-01-13 07:13 UTC, RedBrogdon commented on cookbook/pubspec.yaml
> +  # The following line ensures that the Material Icons font is
You can clear out all these boilerplate comments.

2021-01-13 07:13 UTC, RedBrogdon commented on cookbook/pubspec.yaml
> +    - assets/
Any assets used in these examples are going to be a problem for DartPad.

2021-01-13 07:13 UTC, RedBrogdon commented on cookbook/pubspec.yaml
> +  very_good_analysis: ^1.0.4
Again, no disrespect to VGV, but I'd prefer these to use the analysis options DevRel has for its samples:

https://github.com/flutter/samples/blob/master/provider_shopper/analysis_options.yaml

2021-01-13 07:15 UTC, RedBrogdon commented
> @domesticmouse I think the VGV project is either on dev or master....

Dev would be my preference. To avoid having to migrate these, @domesticmouse, I've asked VGV to start them off opted-in to null safety.

If this is going to royally screw with your CI setup, though, we should talk about it.

2021-01-14 03:57 UTC, matthew-carroll commented on cookbook/lib/main.dart
> +            leading: UnconstrainedBox(
No idea why it's there. I'll remove it.

2021-01-14 03:58 UTC, matthew-carroll commented on cookbook/pubspec.yaml
> +  golden_toolkit: ^0.9.0-nullsafety.0
In our last convo you mentioned that ensuring these UIs don't break is a priority. Goldens are still an effective tool to do that.

2021-01-14 04:08 UTC, matthew-carroll commented
@RedBrogdon I made adjustments for all your comments.

@RedBrogdon and @domesticmouse can you two figure out the CI situation? I'm on `dev` and I think Simon was too, so everything should be `dev`-compatible and null-safe.

2021-01-15 05:24 UTC, RedBrogdon approved these changes
LGTM to me, other than the license swap-out. @domesticmouse is working on getting the CI system ready to handle a dev channel project.

2021-01-15 05:24 UTC, RedBrogdon commented on cookbook/lib/app.dart
> +// Copyright 2019 Google LLC
Bah. I didn't realize we still had Apache licensed code in flutter/samples. I need to go hunt this down.

The one I intended for you to used is this one:

```
// Copyright 2020, the Flutter project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.
```

2021-01-17 03:12 UTC, matthew-carroll commented
@domesticmouse I think we're good here in terms of content. Please let me know whenever the CI system is ready for this to land so we can continue with codelab contributions. Thanks.

2021-01-21 13:26 UTC, domesticmouse commented
Hey @matthew-carroll, can you merge in changes from master to this PR?

2021-01-21 21:01 UTC, matthew-carroll commented
@domesticmouse I rebased against master. CI is still failing on the stable. The logs show:

```
error • Target of URI doesn't exist: 'package:plugin_codelab_example/main.dart' • example/test/widget_test.dart:11:8 • uri_does_not_exist
  error • The function 'MyApp' isn't defined • example/test/widget_test.dart:16:29 • undefined_function

2 issues found. (ran in 2.7s)
Error: Process completed with exit code 1.
```

Is that a problem with this PR, or is that something else?

2021-01-21 21:33 UTC, domesticmouse commented
@matthew-carroll it looks like it is me. I'll ping this bug when I've fixed it.

Proof: https://github.com/flutter/codelabs/pull/53/checks?check_run_id=1744888067

2021-01-22 00:20 UTC, domesticmouse commented
Hey @matthew-carroll, please pull and/or rebase this PR again. I have made master green by [temporarily disabling plugin_codelab](https://github.com/flutter/codelabs/pull/54).

2021-01-22 01:59 UTC, domesticmouse commented
I've trialed adding `"cookbook"` to the `./flutter_ci_script_beta.sh` and `./flutter_ci_dev.sh` locally and run over the following warnings and errors:

```
Analyzing cookbook...                                                   

  error • Target of URI doesn't exist: 'package:integration_test/integration_test.dart' •
         integration_test/app_test.dart:10:8 • uri_does_not_exist
  error • Target of URI doesn't exist: 'package:cookbook/main.dart' • integration_test/app_test.dart:12:8 •
         uri_does_not_exist
  error • The function 'run' isn't defined • integration_test/app_test.dart:14:16 • undefined_function
   info • Avoid annotating types for function expression parameters • integration_test/app_test.dart:17:49 •
          avoid_types_on_closure_parameters
  error • Target of URI doesn't exist: 'package:integration_test/integration_test_driver.dart' •
         integration_test/driver.dart:6:8 • uri_does_not_exist
  error • A value of type 'dynamic' can't be returned from the function 'main' because it has a return type of
         'Future<void>' • integration_test/driver.dart:8:24 • return_of_invalid_type
  error • The function 'integrationDriver' isn't defined • integration_test/driver.dart:8:24 • undefined_function
   info • Avoid annotating types for function expression parameters •
          lib/examples/cupertino_download_button.dart:58:26 • avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters •
          lib/examples/cupertino_download_button.dart:58:48 • avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters •
          lib/examples/cupertino_download_button.dart:366:19 • avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters •
          lib/examples/cupertino_download_button.dart:366:41 • avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters •
          lib/examples/cupertino_download_button.dart:366:58 • avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/examples/expandable_fab.dart:25:17 •
          avoid_types_on_closure_parameters
   info • 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. •
          lib/examples/expandable_fab.dart:29:13 • deprecated_member_use
   info • Avoid annotating types for function expression parameters • lib/examples/expandable_fab.dart:48:23 •
          avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/examples/expandable_fab.dart:48:45 •
          avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/examples/expandable_fab.dart:232:17 •
          avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/examples/expandable_fab.dart:232:39 •
          avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/examples/gradient_bubbles.dart:52:25 •
          avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/examples/gradient_bubbles.dart:52:47 •
          avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/examples/gradient_bubbles.dart:200:61 •
          avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/main.dart:39:23 •
          avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/main.dart:39:45 •
          avoid_types_on_closure_parameters
  error • Target of URI doesn't exist: 'package:cookbook/main.dart' • test/widget_test.dart:11:8 •
         uri_does_not_exist
   info • Avoid annotating types for function expression parameters • test/widget_test.dart:14:49 •
          avoid_types_on_closure_parameters
  error • The argument type 'dynamic' can't be assigned to the parameter type 'Widget' •
         test/widget_test.dart:16:29 • argument_type_not_assignable
  error • The function 'MyApp' isn't defined • test/widget_test.dart:16:29 • undefined_function
```

I'd suggest adding `"cookbook"` as follows to the beta and dev CI scripts:

```
declare -ar CODELABS=(
  # Tracking issue: https://github.com/flutter/flutter/issues/74174
  # "add_flutter_to_android_app"
  "cookbook"
  # Tracking issue: https://github.com/flutter/flutter/issues/74203
  # "cupertino_store"
  # Tracking issue: https://github.com/flutter/flutter/issues/74204
  # "firebase-get-to-know-flutter"
  # Tracking issue: https://github.com/flutter/flutter/issues/74205
  # "github-graphql-client"
  # Tracking issue: https://github.com/flutter/flutter/issues/74206
  # "google-maps-in-flutter"
  # Tracking issue: https://github.com/flutter/flutter/issues/74207
  # "plugin_codelab"
  # Tracking issue: https://github.com/flutter/flutter/issues/74208
  # "startup_namer"
  # Tracking issue: https://github.com/flutter/flutter/issues/74209
  # "testing_codelab"
  )
```

I believe the errors are down to not having an integration test. The warnings, however, are mainly stylistic clashes.

2021-01-22 02:00 UTC, domesticmouse requested changes
Add cookbook to the `beta` and `dev` CI scripts.

2021-01-22 02:01 UTC, matthew-carroll commented
@domesticmouse do you know how I can get those lint rules to run in this project, specifically, in my local environment?

2021-01-22 23:53 UTC, domesticmouse commented
As a first draft, you could try running either [`./flutter_ci_script_dev.sh`](https://github.com/flutter/codelabs/blob/master/flutter_ci_script_dev.sh) or [`./flutter_ci_script_beta.sh`](https://github.com/flutter/codelabs/blob/master/flutter_ci_script_beta.sh) locally, after adding your `cookbook` to the list of codelabs. Looking at the script we don't appear to be doing anything that interesting apart from running `flutter analyze` in the project directory, so I'm surprised you aren't already seeing these warnings in your IDE/editor.

2021-01-23 00:54 UTC, matthew-carroll commented
@domesticmouse I'm not sure how this script is working for any projects. It automatically creates `test/widget_test.dart` with the standard counter test. But that test isn't supposed to exist in any of these projects. So it throws a compilation error, but that error is expected given that none of these projects want that widget test.

I can work out the various info-level warnings one by one, but the errors are the critical part, and it's unclear what I can do to prevent them. BTW, I also got errors for the `add_flutter_to_android_app` project when I ran the stable script. They're the same errors that you got when running the `cookbook` project. So I think there's a deeper problem here and I'm not sure what I'm supposed to do about it.

2021-01-23 00:58 UTC, domesticmouse commented
@RedBrogdon can you supply any of the background on why we run `flutter create` as part of this CI pipeline? It's currently breaking all of the codelabs in beta and dev channels. I'd happily drop it from the CI scripts...

2021-01-26 03:08 UTC, matthew-carroll commented
@RedBrogdon since this PR is still waiting to merge, I pushed 4 more recipe implementations so that we can at least move forward with more reviews. Can you take a look at those for the PR?

2021-01-26 06:41 UTC, RedBrogdon requested changes
Just some nits.

2021-01-26 06:41 UTC, RedBrogdon commented on cookbook/lib/examples/drag_and_drop.dart
> +import 'package:flutter/material.dart';
nit: copyright header

2021-01-26 06:41 UTC, RedBrogdon commented on cookbook/lib/examples/drag_and_drop.dart
> +    imageProvider: AssetImage('assets/chicken-club-chips.png'),
ImageProviders in this file need to be converted to use networked images, since DartPad can't use assets.

See this PR for the URLs for the food and avatar images: https://github.com/flutter/website/pull/5201/files

They're in this form:
https://flutter.dev/docs/cookbook/img-files/effects/split-check/Food1.jpg

2021-01-26 06:41 UTC, RedBrogdon commented on cookbook/lib/examples/parallax.dart
> +import 'package:flutter/cupertino.dart';
nit: copyright header

2021-01-26 06:41 UTC, RedBrogdon commented on cookbook/lib/examples/parallax.dart
> +    // return Parallax(
nit: remove commented-out code.

2021-01-26 06:41 UTC, RedBrogdon commented on cookbook/lib/examples/staggered_animation.dart
> +import 'package:flutter/material.dart';
nit: header

2021-01-26 06:41 UTC, RedBrogdon commented on cookbook/lib/examples/typing_indicator.dart
> +import 'dart:math';
nit: header

2021-01-26 06:41 UTC, RedBrogdon commented on cookbook/lib/items.dart
> +  // CookbookItem('Staggered Animation',             'Transition', Recommendation.yes, (_) => const ExampleStaggeredAnimations()),
Some of these can be uncommented now that the new files are in place.

2021-01-26 06:43 UTC, RedBrogdon commented
> @RedBrogdon can you supply any of the background on why we run `flutter create` as part of this CI pipeline? It's currently breaking all of the codelabs in beta and dev channels. I'd happily drop it from the CI scripts...

That predates my involvement in the repo, so I don't know. It looks like at least a few of the codelabs (startup_namer, for example) are missing their subprojects, possibly to save space. Running flutter create would restore those files before they're built for testing.

2021-01-28 06:10 UTC, RedBrogdon approved these changes
LGTM. @matthew-carroll, is there anything else you wanted to add, or is this ready to merge?

2021-01-28 06:12 UTC, matthew-carroll commented
@RedBrogdon if it passes CI then I'm good to merge. I'll follow up with another PR for the remaining recipes.

2021-01-28 06:40 UTC, domesticmouse commented
@matthew-carroll regarding CI, you'll need to re-rebase to get a working CI that you can then add this project to the dev and beta versions of. Please add it as a commented out codelab in the stable script, and I'll uncomment it after we roll stable.

2021-01-28 06:44 UTC, matthew-carroll commented
@domesticmouse I just pushed a rebased PR with "cookbook" added to the CI scripts.

Since this PR mostly depends upon infra concerns, @domesticmouse or @RedBrogdon please feel free to merge this PR as soon as you're comfortable with it.

2021-01-28 06:52 UTC, domesticmouse approved these changes

2021-01-28 06:53 UTC, domesticmouse commented
I'm happy to land once CI turns green

2021-01-28 06:56 UTC, domesticmouse commented
A bit more tidyup required from [CI log](https://github.com/flutter/codelabs/pull/41/checks?check_run_id=1782017234#step:7:47):

```
   info • Avoid annotating types for function expression parameters • lib/examples/cupertino_download_button.dart:58:26 • avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/examples/cupertino_download_button.dart:58:48 • avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/examples/cupertino_download_button.dart:366:19 • avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/examples/cupertino_download_button.dart:366:41 • avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/examples/cupertino_download_button.dart:366:58 • avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/examples/expandable_fab.dart:25:17 • avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/examples/expandable_fab.dart:48:23 • avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/examples/expandable_fab.dart:48:45 • avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/examples/expandable_fab.dart:232:17 • avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/examples/expandable_fab.dart:232:39 • avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/examples/gradient_bubbles.dart:52:25 • avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/examples/gradient_bubbles.dart:52:47 • avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/examples/gradient_bubbles.dart:200:61 • avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/examples/typing_indicator.dart:62:21 • avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/examples/typing_indicator.dart:62:43 • avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/main.dart:39:23 • avoid_types_on_closure_parameters
   info • Avoid annotating types for function expression parameters • lib/main.dart:39:45 • avoid_types_on_closure_parameters
```

2021-01-28 07:52 UTC, domesticmouse commented
@matthew-carroll flutter format your codelab plz

2021-01-28 10:09 UTC, domesticmouse commented
I'm landing this as is and fixing the formatting in a follow up PR

2021-01-28 10:09 UTC, merged