Add finished code for new codelab for TensorFlow Recommenders + Flutter
flutter/codelabs pull request #536
Opened 2022-04-26 13:24 UTC by windmaple

This codelab demos how to use:

- TensorFlow Recommenders to train a retrieval and a ranking model for movie recommendations
- TensorFlow Serving to serve the models
- Flutter to create a cross-platform app to display recommended movies

This first PR submits the finished code to get feedback. Step-by-step code will be submitted later.

2022-04-26 23:50 UTC, domesticmouse requested changes

2022-04-27 01:50 UTC, domesticmouse approved these changes

2022-04-27 02:05 UTC, windmaple commented on .github/workflows/flutter-ci.yml
> +      - uses: subosito/flutter-action@d8687e6979e8ef66d2b2970e2c92c1d8e801d7bf
Sorry, accidentally merged this. Reverted now.

2022-04-27 02:10 UTC, domesticmouse commented
I'll land when the CI turns green

2022-04-27 03:35 UTC, windmaple commented
Seems CI itself is broken on Mac?

>>>>>>>>>>>>>>>>>>>>
IO  : Retry #5 for GET https://pub.dartlang.org/api/packages/fake_async...
IO  : HTTP GET https://pub.dartlang.org/api/packages/fake_async
    | Accept: application/vnd.pub.v2+json
    | user-agent: Dart pub 2.17.0-266.5.beta
IO  : HTTP error:
    | SocketException: Failed host lookup: 'pub.dartlang.org' (OS Error: nodename nor servname provided, or not known, errno = 8)

2022-04-27 06:43 UTC, merged