Migrate testing_codelab Integration tests
flutter/codelabs pull request #71
Opened 2021-02-09 11:33 UTC by abd99

Added new integration tests based on the new package. Will remove the old tests when the update to the codelab goes live.

/cc @domesticmouse

2021-02-09 23:00 UTC, domesticmouse approved these changes
LGTM, but I'd love a review from @johnpryan to confirm =)

2021-02-10 00:53 UTC, johnpryan requested changes

2021-02-10 00:53 UTC, johnpryan commented on testing_codelab/step_07/integration_test/driver.dart
> +    responseDataCallback: (data) async {
This is more of a workaround for https://github.com/flutter/flutter/issues/74930, I would add a comment indicating that, or remove this altogether unless the codelab involves opening this in chrome://tracing.

2021-02-10 00:53 UTC, johnpryan commented on testing_codelab/step_07/integration_test/app_test.dart
> +          await scroller.animateTo(
I think we should recommend using [`tester.drag()`](https://api.flutter.dev/flutter/flutter_test/WidgetController/drag.html) instead and remove the `controller: ScrollController(),` lines from the app

2021-02-10 00:53 UTC, johnpryan commented on testing_codelab/step_07/integration_test/app_test.dart
> +        await binding.watchPerformance(() async {
I would try to show an example of 1. a test and 2. a performance benchmark. The first test is a benchmark, and this looks more like a test, so I would remove the `traceAction` and watchPerformance` wrappers.

2021-02-10 03:42 UTC, abd99 commented on testing_codelab/step_07/integration_test/driver.dart
> +    responseDataCallback: (data) async {
I've mentioned this in the codelab note. I can still remove it if it feels unnecessary or something we should avoid for a codelab.

These are the exact word that I've used:
"Note: Writing a custom implementation for the responseDataCallback isn't necessary. However, doing so allows us to store the test data into separate files which makes it easier to further evaluate the test reports. If you omit this step, all the response data will be stored in one single file named integration_response_data.json."

2021-02-10 03:58 UTC, abd99 commented on testing_codelab/step_07/integration_test/app_test.dart
> +          await scroller.animateTo(
I actually used the pre-existing E2E test in the testing sample as an inspiration to write these new tests. How can I forget that there are easier ways! Thanks for suggesting this. I'm using `tester.fling()` now.

2021-02-10 03:59 UTC, abd99 commented on testing_codelab/step_07/integration_test/app_test.dart
> +        await binding.watchPerformance(() async {
This makes complete sense. I'll change it. Thanks!

2021-02-10 04:40 UTC, abd99 commented
PTAL @johnpryan, I've made the changes. I would also recommend you take a look at the codelab while reviewing this as it will help you understand how this code is being used. Brett has tagged you there.

2021-02-10 17:29 UTC, johnpryan approved these changes

2021-03-09 07:23 UTC, abd99 commented
PTAL @johnpryan, I have resolved the conflicts and made the same changes as the testing sample. The codelab doc is also in a much better place to be released now.

2021-03-09 07:59 UTC, domesticmouse approved these changes

2021-03-09 07:59 UTC, domesticmouse commented on testing_codelab/step_05/pubspec.yaml
>    flutter_driver: # new
Can we line up the `#new`s? Makes for easier cut'n'paste into the codelab doc =)

2021-03-09 07:59 UTC, domesticmouse commented on testing_codelab/step_04/pubspec.yaml
> +  integration_test: ^1.0.1    # new
Also these `#new`s

2021-03-09 07:59 UTC, domesticmouse commented on testing_codelab/step_06/pubspec.yaml
> +  integration_test: ^1.0.1    # new
And here

2021-03-09 07:59 UTC, domesticmouse commented on testing_codelab/step_07/pubspec.yaml
> +  integration_test: ^1.0.1    # new
and here.

2021-03-09 10:59 UTC, abd99 commented on testing_codelab/step_05/pubspec.yaml
>    flutter_driver: # new
Of course, we can. Pushing changes soon.

2021-03-09 17:54 UTC, johnpryan approved these changes

2021-03-10 06:17 UTC, domesticmouse commented
Landing. Thanks @abd99!

2021-03-10 06:17 UTC, merged