Null safe migration + desktop runners
flutter/codelabs pull request #85
Opened 2021-03-28 21:27 UTC by domesticmouse

2021-03-28 21:28 UTC, domesticmouse commented
Hey @abd99, if you have half an hour to spot check this null safety migration I'd be most appreciative =)

2021-03-29 00:50 UTC, abd99 commented
Hey @domesticmouse, thanks for pinging me on this!

I thought that we are waiting until all the dependencies get migrated. Are we moving forward with `unsound null-safety` for now because the null-safe version of the `integration_test` package isn't on stable yet?

2021-03-29 01:07 UTC, abd99 commented
@domesticmouse, I just checked. It isn't working with unsound null-safety either. I'm getting a batch of similar errors:
`Error: A library can't opt out of null safety by default, when using sound null safety.`

I think we'll have to put a hold on this before the required dependencies are in stable.
Should we ask the team if the migrated packages can be released in the next hotfix or something? I believe they are already migrated on master. The next stable release would normally take months.

2021-03-29 01:18 UTC, abd99 commented
In case you don't know or forgot, the `integration_test` package is now a part of the `flutter/flutter` repo itself.

2021-03-29 03:00 UTC, domesticmouse commented
I'm curious where you are seeing the errors, as the CI is all green. What are we not testing in the CI pipeline?

As for holding off this change until all the bits land in stable sounds like the right approach. I believe both of the outstanding packages are in master, but it won't be until next quarter that we see it in stable.

Thoughts @RedBrogdon?

2021-03-29 03:08 UTC, abd99 commented
> I'm curious where you are seeing the errors, as the CI is all green. What are we not testing in the CI pipeline?

I got those errors on my local environment. We aren't running integration tests on the CI pipeline. I think we should do something about it. We always won't be able to manually test it. I'll try setting up an emulator on GitHub actions and try running integration tests at least in debug mode.

2021-03-29 03:20 UTC, domesticmouse commented
Something for a separate PR methinks. Having unchecked tests sounds bad. 😎

2021-05-18 21:01 UTC, abd99 requested changes
Thanks a lot for this PR, @domesticmouse! 

A few changes are needed. Before that:

Please change
```
integration_test: ^1.0.1
```

to

```
integration_test: 
    sdk: flutter 
```


You can also remove the `test_driver` directory from `step_07` and the `flutter_driver` dependencies from all the steps.

Let me know if you need any more clarification. This was my first real review =)

2021-05-18 21:04 UTC, abd99 commented
> Something for a separate PR methinks. Having unchecked tests sounds bad. 😎

I tried setting up an emulator on GitHub Actions, but couldn't get the test to run on it. I think we'll have to discuss about this in our upcoming meeting.

2021-05-18 21:28 UTC, domesticmouse commented
> I think we'll have to discuss about this in our upcoming meeting.

Sweet =)

2021-05-19 21:55 UTC, domesticmouse commented on testing_codelab/step_03/macos/.gitignore
> +# Flutter-related
We have a mission to make codelabs available on all platforms that they work. So yeah, we kinda do. =)

2021-05-19 22:04 UTC, domesticmouse commented
Hey @abd99, is this now safe to land?

2021-05-20 10:07 UTC, abd99 commented
LGTM, thanks!

2021-05-20 10:07 UTC, abd99 approved these changes

2021-05-24 04:15 UTC, merged