Initial Firebase 102 code (Do not merge)
flutter/codelabs pull request #959
Opened 2022-06-13 17:57 UTC by ericwindmill

This PR is solely to get a review on the complete code of the codelab. It should not be merged.

## Pre-launch Checklist

- [ ] I read the [Effective Dart: Style] _recently_, and have followed its advice.
- [ ] I signed the [CLA].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Effective Dart: Style]: https://dart.dev/guides/language/effective-dart/style
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2022-06-13 22:45 UTC, domesticmouse commented
Marking as draft as this is WIP

2022-06-13 22:47 UTC, domesticmouse commented on firebase_a_b_test/complete/lib/src/pages/products_list_page.dart
> +                }),
For consistency, do you want to insert a trailing comma after the `}`?

2022-06-13 22:49 UTC, domesticmouse commented on firebase_a_b_test/complete/analysis_options.yaml
> +include: package:flutter_lints/flutter.yaml
Please replace this with the repo `analysis_options.yaml` in the root of the repo. It'll kick out linter warnings for a bunch of things. 

QQ, have you added this project to the repo CI?

2022-06-13 22:50 UTC, domesticmouse commented on firebase_a_b_test/complete/lib/src/pages/product_details_page.dart
> +  }) : super(key: key);
You'll know CI is working when the build fails due to this causing a linter warning for `use_super_parameters`.

2022-06-13 22:51 UTC, domesticmouse requested changes
Modify the `analysis_options.yaml` and add this to CI.

2022-06-14 22:47 UTC, domesticmouse approved these changes
I'm happy to land this once the tests turn green

2022-06-16 22:50 UTC, domesticmouse requested changes

2022-06-16 22:50 UTC, domesticmouse commented on firebase-monitor-your-flutter-app/complete/lib/firebase_options.dart
> +// Copyright 2020 The Flutter Authors. All rights reserved.
I suspect this should be 2022

2022-06-16 22:50 UTC, domesticmouse commented on firebase-monitor-your-flutter-app/complete/lib/src/data/seed_data.dart
> +// This data should be imported via running the Firebase emulator suite with the --import flag
Please reformat to show actual command line usage like:

```
// this data should be imported as follows:
//   $ program --import <file>
```

2022-06-16 22:50 UTC, domesticmouse commented on firebase-monitor-your-flutter-app/complete/lib/src/pages/product_details_page.dart
> +    // ...
Whats required here?

2022-06-16 22:50 UTC, domesticmouse commented on firebase-monitor-your-flutter-app/complete/remoteconfig.template.json
> +{}
nit: add newline

2022-06-16 22:50 UTC, domesticmouse commented on firebase-monitor-your-flutter-app/complete/pubspec.yaml
> +  build_runner: ^2.1.11
There's a couple of deps here that should be under `dev_dependencies`, like `mockito`, `build_runner` and `json_serializable`.

2022-06-16 22:55 UTC, ericwindmill commented on firebase-monitor-your-flutter-app/complete/pubspec.yaml
> +  build_runner: ^2.1.11
TIL that `pub add` doesn't distinguish between dev and dependencies

2022-06-16 22:57 UTC, domesticmouse commented on firebase-monitor-your-flutter-app/complete/pubspec.yaml
> +  build_runner: ^2.1.11
You want `flutter pub add --dev pkgname` 😎

2022-06-16 22:58 UTC, ericwindmill commented on firebase-monitor-your-flutter-app/complete/lib/src/pages/product_details_page.dart
> +    // ...
This would be where, in real life, an item is added to a shopping cart. I did not implement a shopping cart because the part that matters for this codelab is the FirebaseAnalytics logging. I'm not opposed to 'finishing' the app, if thats the status quo for this type of thing.

2022-06-17 02:50 UTC, domesticmouse commented on .idea/.gitignore
> +# Default ignored files
It's probably worth `.gitignore`ing this whole directory, as I'm not going to keep the projects listed in `codelabs.iml` up to date.

2022-06-17 02:53 UTC, domesticmouse requested changes
Drop the `.idea` directory and we are good to land

2022-06-17 22:47 UTC, domesticmouse approved these changes

2022-06-17 22:47 UTC, merged